common: &common
  app_params:
    appid: 123
    format: json
    device_id: c3237e03e39529470488749ba4191920f11cbc93
    locale: en
    ip: 8.8.8.8
    offer_types: 112
  api_key: fb7e5d0b8535d90202b072cdcf75ca62d20d2439
  url: http://api.sponsorpay.com/feed/v1/offers.json
  timeout: 3
  open_timeout: 3

development:
  <<: *common

production:
  <<: *common

test:
  <<: *common
